apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: reviews 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews 
    spec:
      containers:
        - name: reviews 
          image: sh360acr.azurecr.io/reviews
          env:
          - name: sql_server_url
            value: jdbc:postgresql://localhost:5432/reviewsdb
          - name: sql_user_name
            value: admin
          - name: sql_user_password
            value: Passw0rd!     
          ports:
          - containerPort: 80
